Milestone: Hello-Microverse Project
malikhaiderkhan/Hello-world pull request #1
Opened 2023-04-25 14:29 UTC by malikhaiderkhan

I updated the index.html and style.css file by adding class attribute in it and modify the README.md file according to the reviewers and also added LICENSE to the repository.

2023-04-25 14:33 UTC, malikhaiderkhan commented
It is a simple Microverse project using html and css.

2023-04-25 20:51 UTC, ademibowale requested changes
## STATUS: Changes Required :recycle:

### Hi @malikhaiderkhan , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight 🥇

- Descriptive Pull Request title and summary. ✔️
- Good use of Github flow ✔️

### Changes Required

- [x]  _Please check the comments under the review._
- [x] Please kindly modify your readme file to suit the miroverse readme template  [This Template](https://github.com/microverseinc/readme-template/blob/master/README.md)._  

- [ ] I suggest you to pull out the readme from your main branch to the feature branch (html-css) and modify it to suit the project and its personal details. As currently in your feature branch all i can see in your README file is a text (Hello World). Please kindly work on tis
    - Please Note: while walking through your readme file from the main branch, i notice the MIT licence is not properly added to your project, Kindly work on it

- [ ] As stated in the project requirement, I would kindly suggest you give your `h1` in your `HTML file` a class name so that the class name can be used to style the content in the CSS file

E.g
```HTML
<h1 class="header">Hello Microverse</h1>
```

- [ ] In your `CSS file`, I would also suggest you use the class name you have given the `h1` in the `HTML` to style your content, this is the requirement of this project and this will also show your ability to follow any requirement given in a project.

E.g
```CSS
.header {
  color: lightgreen;
}
```

- [ ] Lastly, I would also suggest you work on the pull request title to make it more descriptive and denote what you have in the project milestone and this shows some level of professionalism when working on your project. I would suggest something like this "Milestone: Hello-Microver Project"

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 16:14 UTC, Strangeal requested changes
Hi @malikhaiderkhan, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Alt Text](https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif)

 ## Required Changes ♻️
- [ ] Congratulations 🎉 🥳 on the impressive work you've done so far. I've made some suggestions below to help you improve your project so kindly take a look at it and if you don't understand anything please don't hesitate to ask. Best of luck!🤞 🍀

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 16:14 UTC, Strangeal commented on README.md
> +
- [x] As specified by the previous reviewer you need to customize the readme template based on the needs of your project. Kindly remove the `live demo` section as this project doesn’t have a live version so it will be misleading to have it in your `README`. Please remember to remove it from your `Table of content` as well.

2023-04-26 16:14 UTC, Strangeal commented on README.md
>  Clone this repository to your computer
As specified by the previous reviewer you need to customize the readme template based on the needs of your project. This section of the `README` should outline the steps a user can use to clone your repository into their local machine. Example:
```sh
  cd Hello-Microverse
  git clone git@github.com:malikhaiderkhan/Hello-world.git
```

2023-04-26 16:14 UTC, Strangeal commented on README.md
- [ ] As specified by the previous reviewer you need to customize the readme template based on the needs of your project. Kindly add instructions on how users can install all dependencies of your project after cloning it into their local machine. Example: 
```
npm install
```

2023-04-26 16:14 UTC, Strangeal commented on README.md
> +To run tests, run the following command: Open index.html with lite server in vscode.
- [x]As specified by the previous reviewer you need to customize the readme template based on the needs of your project. Kindly add a step by step instructions on how users can run `linters` and check for errors after cloning your repository. This way they will not find themselves wanting trying to figure out how to run tests. Example:

### Run Tests
To track linter errors locally follow these steps:  

Download all the dependencies run:
```
npm install
```
Track HTML linter errors run:
```
npx hint .
```
Track CSS linter errors run:
```
npx stylelint "**/*.{css,scss}"
```

2023-04-26 16:14 UTC, Strangeal commented on README.md
> +Coming Soon
- [x]  As specified by the previous reviewer you need to customize the readme template based on the needs of your project. Kindly remove the `deployment` section as this project is not going to be deployed. You should include it in projects that have live demos. Please remember to remove it from your `Table of content` as well.

2023-04-26 18:59 UTC, malikhaiderkhan commented
@Strangeal please just check it can I fulfill your requirements or not?

2023-04-26 19:53 UTC, malikhaiderkhan reviewed
I updated the index.html and style.css file by adding class attribute in it and modify the README.md file according to the reviewers and also added LICENSE file to the repository.

2023-04-26 20:04 UTC, vickymarz approved these changes
Hi @malikhaiderkhan , 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- Requested changes implemented✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 20:53 UTC, merged